Pv2 2439 performance improvement
SkillsFundingAgency/das-payments-V2-matched-learner pull request #10
Opened 2021-04-22 11:02 UTC by hardik-desai-kcl

2021-04-23 11:35 UTC, tom-gough requested changes

2021-04-23 12:17 UTC, hardik-desai-kcl commented on src/SFA.DAS.Payments.MatchedLearner.Application/Data/PaymentsContext.cs
>              modelBuilder.ApplyConfiguration(new LatestSuccessfulJobModelConfiguration());
yes, it is required because its a view and it doesn't have normal primary key

2021-04-23 12:23 UTC, hardik-desai-kcl commented on src/SFA.DAS.Payments.MatchedLearner.AcceptanceTests/Bindings/SmokeTestBindings.cs
> +        public void ThenTheResultShouldBeA()
done

2021-04-23 12:23 UTC, hardik-desai-kcl commented on src/SFA.DAS.Payments.MatchedLearner.AcceptanceTests/Bindings/SmokeTestBindings.cs
> +            foreach (var failedRequest in _context.FailedRequests)
done

2021-04-23 12:23 UTC, hardik-desai-kcl commented on src/SFA.DAS.Payments.MatchedLearner.Application.UnitTests/MappersTests/MatchedLearnerDtoMapperTests/MapTestsWithMultipleDataLockEvents.cs
> +                    //Apprenticeship = new Apprenticeship(),
done

2021-04-23 12:23 UTC, hardik-desai-kcl commented on src/SFA.DAS.Payments.MatchedLearner.Application.UnitTests/MappersTests/MatchedLearnerDtoMapperTests/MapTestsWithMultipleDataLockEvents.cs
> +                    //Apprenticeship = new Apprenticeship(),
done

2021-04-23 12:23 UTC, hardik-desai-kcl commented on src/SFA.DAS.Payments.MatchedLearner.Application.UnitTests/MappersTests/MatchedLearnerDtoMapperTests/MapTestsWithMultipleDataLockEvents.cs
> +                    //Apprenticeship = new Apprenticeship(),
done

2021-04-23 12:23 UTC, hardik-desai-kcl commented on src/SFA.DAS.Payments.MatchedLearner.Application/Data/MatchedLearnerDataLockDataDto.cs
> +    public class MatchedLearnerDataLockDataDto
done

2021-04-23 12:45 UTC, hardik-desai-kcl commented on src/SFA.DAS.Payments.MatchedLearner.AcceptanceTests/Bindings/SmokeTestBindings.cs
>          public void WhenWeCallTheApiWithALearnerThatDoesNotExist()
done

2021-04-23 12:45 UTC, hardik-desai-kcl commented on src/SFA.DAS.Payments.MatchedLearner.Application.UnitTests/RepositoryTests/PaymentsDataLockRepositoryTests/WhenGettingDataLockEvents.cs
> +            //_dataLockEvent.PriceEpisodes.Clear();
done

2021-04-23 12:46 UTC, hardik-desai-kcl commented on src/SFA.DAS.Payments.MatchedLearner.Api/Startup.cs
> +            services.AddApplicationInsightsTelemetry();
Nlog was already configured, I have added two loggers for Service class and repo class

2021-04-23 13:21 UTC, tom-gough approved these changes

2021-04-26 07:47 UTC, ChughAkshay approved these changes

2021-04-27 09:14 UTC, tom-gough approved these changes

2021-04-28 15:06 UTC, tom-gough approved these changes

2021-05-07 08:30 UTC, merged