Pv2-2592 ei redesign
SkillsFundingAgency/das-payments-V2-matched-learner pull request #16
Opened 2021-08-20 10:33 UTC by hardik-desai-kcl

2021-08-20 18:11 UTC, AkshayBanifatsyevichChugh submitted a review, later dismissed

2021-08-23 08:48 UTC, hardik-desai-kcl commented on src/SFA.DAS.Payments.MatchedLearner.Api/Properties/launchSettings.json
> +        "EnvironmentName": "Development"
this variable is only used at Local development time so no need to change

2021-08-23 08:49 UTC, hardik-desai-kcl commented on src/SFA.DAS.Payments.MatchedLearner.Data/Contexts/MatchedLearnerDataContext.cs
> +        }
these two methods deletes existing data from Matched Learner DB just before latest submission data is imported

2021-08-23 08:52 UTC, hardik-desai-kcl commented on src/SFA.DAS.Payments.MatchedLearner.Application/MatchedLearnerDataImportService.cs
> +            //if current collection is 1 then only try remove current collection data otherwise remove current + previous collection data
removed

2021-08-23 09:15 UTC, hardik-desai-kcl commented on src/SFA.DAS.Payments.MatchedLearner.Data/Entities/ApprenticeshipModel.cs
> +        // public List<ApprenticeshipPauseModel> ApprenticeshipPauses { get; set; }
removed

2021-08-23 09:15 UTC, hardik-desai-kcl commented on src/SFA.DAS.Payments.MatchedLearner.Data/Contexts/MatchedLearnerDataContext.cs
> +        }
removed

2021-08-23 09:27 UTC, AkshayBanifatsyevichChugh approved these changes

2021-08-25 14:53 UTC, AkshayBanifatsyevichChugh approved these changes

2021-08-25 14:53 UTC, AkshayBanifatsyevichChugh commented on src/SFA.DAS.Payments.MatchedLearner.Data/SqlAzureIdentityTokenProvider.cs
> +namespace SFA.DAS.Payments.MatchedLearner.Data
3 classes and 1 interface in 1 file, hard to read

2021-08-25 14:53 UTC, AkshayBanifatsyevichChugh commented on src/SFA.DAS.Payments.MatchedLearner.Data/SqlAzureIdentityTokenProvider.cs
> +        private static readonly Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProvider AzureServiceTokenProvider = new Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProvid
Few things:

- fully qualified type name used but not needed
- variable marked as static but access is private and class is non static, not sure if intended
- doesn't follow underscore convention
- if will be changed to non static, should move assignment of variable to constructor

2021-08-25 14:53 UTC, AkshayBanifatsyevichChugh commented on src/SFA.DAS.Payments.MatchedLearner.Data/SqlAzureIdentityTokenProvider.cs
> +        }
network call done synchronously

2021-11-16 13:45 UTC, tom-gough requested changes

2021-11-16 13:45 UTC, tom-gough commented on src/SFA.DAS.Payments.MatchedLearner.Application.UnitTests/RepositoryTests/MatchedLearnerRepositoryTests/WhenGettingDataLockEvents.cs
>              _dataLockEvent.AcademicYear = 2021;
some commented out code in this class

2021-11-16 13:53 UTC, tom-gough approved these changes

2021-11-16 14:46 UTC, tom-gough approved these changes

2021-11-16 14:51 UTC, AkshayBanifatsyevichChugh submitted a review, later dismissed

2021-12-14 11:42 UTC, tom-gough approved these changes

2021-12-16 16:58 UTC, AkshayBanifatsyevichChugh approved these changes

2021-12-16 17:10 UTC, AkshayBanifatsyevichChugh approved these changes

2022-01-13 15:00 UTC, AkshayBanifatsyevichChugh submitted a review, later dismissed

2022-01-27 11:14 UTC, AkshayBanifatsyevichChugh approved these changes

2022-02-07 15:38 UTC, AkshayBanifatsyevichChugh submitted a review, later dismissed

2022-02-09 09:31 UTC, AkshayBanifatsyevichChugh approved these changes

2022-02-22 13:32 UTC, merged