Pv2 2118 collate data
SkillsFundingAgency/das-payments-V2-matched-learner pull request #2
Opened 2020-10-07 14:53 UTC by carlbm

No acceptance tests yet - they are coming in a different task

2020-10-08 13:03 UTC, hardik-desai-kcl requested changes

2020-10-08 13:13 UTC, carlbm commented on src/MatchedLearnerApi.Application/Models/DatalockEvent.cs
> +        //public DateTime StartDate { get; set; }
✔️

2020-10-08 13:35 UTC, carlbm commented on src/MatchedLearnerApi.Application/Mappers/MatchedLearnerResultMapper.cs
> +                            ApprenticeshipEmployerType = failure.Apprenticeship.ApprenticeshipEmployerType,
This has been changed in the acceptance tests branch

2020-10-08 13:35 UTC, carlbm commented on src/MatchedLearnerApi.Application/Mappers/MatchedLearnerResultMapper.cs
> +                            ApprenticeshipEmployerType = payablePeriod.ApprenticeshipEmployerType,
This has been changed in the acceptance tests branch

2020-10-08 13:36 UTC, carlbm commented on src/MatchedLearnerApi.Application/PaymentsContext.cs
> +
Not required as it follows the convention

2020-10-08 13:37 UTC, carlbm commented on src/MatchedLearnerApi.Types/TrainingDto.cs
> +        public string Status { get; set; } //todo not used - why?
✔️

2020-10-09 09:50 UTC, carlbm commented on src/MatchedLearnerApi.Application/Mappers/MatchedLearnerResultMapper.cs
> +                        Periods = priceEpisode.PayablePeriods.Select(payablePeriod => new PeriodDto
I've changed this to split it out into smaller functions

2020-10-09 12:44 UTC, carlbm commented on src/MatchedLearnerApi.Application/PaymentsContext.cs
> +        public PaymentsContext(IConfiguration configuration)
✔️

2020-10-09 12:59 UTC, carlbm commented on src/MatchedLearnerApi.Application/Repositories/EmployerIncentivesRepository.cs
> +                    .Where(y => y.Ukprn == ukprn && y.Uln == uln).OrderByDescending(y => y.AcademicYear).ThenByDescending(y => y.IlrSubmissionWindowPeriod).Select(y => y.AcademicYear).FirstOrDefault(
✔️

2020-10-09 13:02 UTC, carlbm commented on src/MatchedLearnerApi/IoC/MatchedLearnerApiRegistry.cs
> +        public void Register(IServiceCollection services)
✔️

2020-10-28 10:41 UTC, carlbm commented
Superceded

2020-10-28 10:41 UTC, closed without merging