Revert Merge pull request PV2-2592-EI-redesign
SkillsFundingAgency/das-payments-V2-matched-learner pull request #25
Opened 2022-03-01 13:38 UTC by hardik-desai-kcl

2022-03-02 10:29 UTC, EwanNoble requested changes

2022-03-02 10:29 UTC, EwanNoble commented on azure-pipelines.yml
>    batch: true
This file shouldn't be reverted

2022-03-02 10:29 UTC, EwanNoble commented on pipeline-templates/job/code-build.yml
> -jobs:
This shouldn't be reverted

2022-03-02 10:29 UTC, EwanNoble commented on pipeline-templates/job/dacpac-build.yml
> -jobs:
This shouldn't be reverted

2022-03-14 17:11 UTC, AkshayBanifatsyevichChugh approved these changes

2022-03-17 11:19 UTC, EwanNoble approved these changes

2022-03-17 11:42 UTC, merged