Pv2 2833 learner crosses academic year
SkillsFundingAgency/das-payments-V2-matched-learner pull request #32
Opened 2022-06-21 15:29 UTC by AkshayBanifatsyevichChugh

2022-06-22 13:11 UTC, hardik-desai-kcl requested changes

2022-06-22 13:11 UTC, hardik-desai-kcl commented on src/SFA.DAS.Payments.MatchedLearner.Data/Repositories/MatchedLearnerRepository.cs
> +            var latestProviderSubmittedJob = await GetLatestSubmissionJobForProvider(ukprn);
not sure how it was handled in previous code but we should add a check where we can find a provide but we cant fine a learner in that case we should return 404

2022-06-22 15:01 UTC, AkshayBanifatsyevichChugh commented on src/SFA.DAS.Payments.MatchedLearner.AcceptanceTests/TestRepository.cs
> +            VALUES  (@dataLockEventId, Convert(varchar, @AcademicYear + @collectionPeriod) + '-104-01/08/2020', 1, 1, 100, 1, @testDateTime, @apprenticeshipId),
change applied

2022-06-22 15:02 UTC, AkshayBanifatsyevichChugh commented on src/SFA.DAS.Payments.MatchedLearner.Application.UnitTests/RepositoryTests/MatchedLearnerRepositoryTests/WhenGettingDataLockEvents.cs
> +            await AddDataLockToDb(_dataLockEvent);
These specific tests don't test the header values, they only test the DLE count and the Payable / Non Payable period object. I've added new unit tests to this class which test the header and these new tests are populating the Submission Job table via await AddSubmissionJobToDb(_submissionJob).

2022-06-23 09:34 UTC, hardik-desai-kcl submitted a review, later dismissed

2022-07-26 09:32 UTC, hardik-desai-kcl approved these changes

2022-08-31 09:25 UTC, merged